name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev googletest g++ gcovr
        # Компилируем gtest, если нужно (иногда требуется)
        cd /usr/src/googletest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib
    - name: Build
      run: make all
    - name: Run tests
      run: make test
    - name: Generate coverage
      run: |
        make coverage
        gcovr --xml --root . --exclude-unreachable-branches --exclude-throw-branches > coverage.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml
        fail_ci_if_error: true
