name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ gcovr
        wget https://github.com/google/googletest/archive/refs/tags/release-1.14.0.tar.gz
        tar -xzf release-1.14.0.tar.gz
        cd googletest-release-1.14.0
        mkdir build && cd build
        cmake ..
        sudo make install
    - name: Build
      run: make all
    - name: Run tests
      run: make test
    - name: Generate coverage
      run: |
        make coverage
        gcovr --xml --root . --exclude-unreachable-branches --exclude-throw-branches > coverage.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml
        fail_ci_if_error: true
